// Paleta curada de colores con nombre en español, pensada para bodas/eventos
// -- se usa como atajo visual en ColorPickerField; el usuario siempre puede
// seguir eligiendo un hex libre con el selector nativo o el input de texto.
export const NAMED_COLORS = [
  { name: 'Dorado', hex: '#D4AF37' },
  { name: 'Oro rosa', hex: '#B76E79' },
  { name: 'Champagne', hex: '#F1E2C3' },
  { name: 'Marfil', hex: '#FFFDD0' },
  { name: 'Blanco hueso', hex: '#F0EAD6' },
  { name: 'Blanco', hex: '#FFFFFF' },
  { name: 'Rosa palo', hex: '#E8C4C4' },
  { name: 'Rosa viejo', hex: '#C48793' },
  { name: 'Fucsia', hex: '#C2185B' },
  { name: 'Coral', hex: '#FF6F61' },
  { name: 'Terracota', hex: '#E2725B' },
  { name: 'Durazno', hex: '#FFCBA4' },
  { name: 'Mostaza', hex: '#E1AD01' },
  { name: 'Salvia', hex: '#9CAF88' },
  { name: 'Verde esmeralda', hex: '#50C878' },
  { name: 'Verde botella', hex: '#1B4332' },
  { name: 'Turquesa', hex: '#30D5C8' },
  { name: 'Azul cielo', hex: '#87CEEB' },
  { name: 'Azul polvo', hex: '#A9C6E8' },
  { name: 'Azul marino', hex: '#14213D' },
  { name: 'Azul petróleo', hex: '#0A5C6E' },
  { name: 'Lavanda', hex: '#C8A2C8' },
  { name: 'Violeta', hex: '#6B3FA0' },
  { name: 'Borgoña', hex: '#722F37' },
  { name: 'Vino tinto', hex: '#4A0E1E' },
  { name: 'Chocolate', hex: '#4B2E2B' },
  { name: 'Cobre', hex: '#B87333' },
  { name: 'Gris perla', hex: '#D9D6CE' },
  { name: 'Plateado', hex: '#B8B8B8' },
  { name: 'Negro elegante', hex: '#0A0A0A' },
]
